# Generated by Django 4.1 on 2022-08-26 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_preprocessing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
