# Generated by Django 4.1 on 2022-08-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_preprocessing_raw_data_id_preprocessing_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessing',
            name='raw_data_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='preprocessing',
            name='result',
            field=models.TextField(null=True),
        ),
    ]
