# Generated by Django 4.1 on 2022-08-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessing',
            name='raw_data_id',
        ),
        migrations.RemoveField(
            model_name='preprocessing',
            name='result',
        ),
        migrations.AddField(
            model_name='preprocessing',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preprocessing',
            name='review_tokens_stemmed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preprocessing',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
