# Generated by Django 4.1 on 2022-09-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_preprocessing_raw_data_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaenen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('cluster', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
