# Generated by Django 4.1 on 2022-09-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_kaenen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmoteKnn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('cluster', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
